#pragma once

#include "obse_common/obse_version.h"
#include "IVersionCheck.h"

#define PLUGIN_AUTHOR "RealArenaTraining"
#define PLUGIN_NAME_SHORT "RealArenaTraining"
#define PLUGIN_NAME_LONG "Real Arena Training"

#define PLUGIN_VERSION_MAJOR 1
#define PLUGIN_VERSION_MINOR 0
#define PLUGIN_VERSION_BUILD 0

#define PLUGIN_LOG_FILE "\\My Games\\" GAME_SAVE_FOLDER_NAME("Oblivion") "\\OBSE\\" PLUGIN_LOG_FILE_NAME(PLUGIN_NAME_SHORT)

#define SDK_VERSION_STRING VERSION_TO_STRING(OBSE_VERSION_INTEGER, OBSE_VERSION_INTEGER_MINOR, OBSE_VERSION_INTEGER_HOTIFX)
#define PLUGIN_VERSION_STRING VERSION_TO_STRING(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)
#define PLUGIN_VERSION_DLL MAKE_EXE_VERSION(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)
#define PLUGIN_VERSION_INFO PLUGIN_NAME_SHORT " v%s (0x%08X) (SDK v%s)", PLUGIN_VERSION_STRING, PLUGIN_VERSION_DLL, SDK_VERSION_STRING

#define MINIMUM_RUNTIME_VERSION OBLIVION_VERSION_1_2_416
#define SUPPORTED_RUNTIME_VERSION RUNTIME_VERSION
#define SUPPORTED_RUNTIME_VERSION_STRICT true
#define SUPPORTED_RUNTIME_VERSION_CS CS_VERSION

#define REALARENATRAINING_SKILL_PROGRESS_PER_INTERACTION 1.0f
#define REALARENATRAINING_ENABLE_TRAINING_LOGGING 1
#define REALARENATRAINING_MAX_TRAINING_LOGS 256
#define REALARENATRAINING_ENABLE_CANDIDATE_LOGGING 1
#define REALARENATRAINING_MAX_CANDIDATE_LOGS 128
#define REALARENATRAINING_MAX_REJECTED_TRAINING_LOGS 128
#define REALARENATRAINING_ENABLE_HOOK_ENTRY_LOGGING 1
#define REALARENATRAINING_MAX_HOOK_ENTRY_LOGS 192
