#pragma once
#include "obse_common/obse_version.h"
#include "IVersionCheck.h"

#define PLUGIN_AUTHOR "Ez0n3"

#define PLUGIN_NAME_SHORT "ez_xobse_plugin_example"
#define PLUGIN_NAME_LONG "Ez xOBSE Plugin Example"

#define PLUGIN_VERSION_MAJOR 1
#define PLUGIN_VERSION_MINOR 0
#define PLUGIN_VERSION_BUILD 0

#define PLUGIN_LOG_FILE "\\My Games\\" GAME_SAVE_FOLDER_NAME("Oblivion") "\\OBSE\\" PLUGIN_LOG_FILE_NAME(PLUGIN_NAME_SHORT)

#define SDK_VERSION_STRING VERSION_TO_STRING(OBSE_VERSION_INTEGER, OBSE_VERSION_INTEGER_MINOR, OBSE_VERSION_INTEGER_HOTIFX)
#define PLUGIN_VERSION_STRING VERSION_TO_STRING(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)

#define PLUGIN_VERSION_DLL MAKE_EXE_VERSION(PLUGIN_VERSION_MAJOR, PLUGIN_VERSION_MINOR, PLUGIN_VERSION_BUILD)
#define PLUGIN_VERSION_INFO PLUGIN_NAME_SHORT " v%s (0x%08X) (SDK v%s)", PLUGIN_VERSION_STRING, PLUGIN_VERSION_DLL, SDK_VERSION_STRING

#define MINIMUM_RUNTIME_VERSION OBLIVION_VERSION_1_2_416
#define SUPPORTED_RUNTIME_VERSION RUNTIME_VERSION
#define SUPPORTED_RUNTIME_VERSION_STRICT false
#define COMPATIBLE(runtimeVersion) (runtimeVersion == SUPPORTED_RUNTIME_VERSION)
#define SUPPORTED_RUNTIME_VERSION_CS CS_VERSION

#define SILT_USE_HOOK_BACKEND 0
#define SILT_DEFAULT_ENABLED 0